In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('Sheet2.csv')

In [3]:
dataset.describe()

Unit price     Quantity  ...  gross income      Rating
count  1000.000000  1000.000000  ...   1000.000000  1000.00000
mean     55.672130     5.510000  ...     15.379369     6.97270
std      26.494628     2.923431  ...     11.708825     1.71858
min      10.080000     1.000000  ...      0.508500     4.00000
25%      32.875000     3.000000  ...      5.924875     5.50000
50%      55.230000     5.000000  ...     12.088000     7.00000
75%      77.935000     8.000000  ...     22.445250     8.50000
max      99.960000    10.000000  ...     49.650000    10.00000

[8 rows x 8 columns]

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Time                     1000 non-null   object 
 1   Date                     1000 non-null   object 
 2   Invoice ID               1000 non-null   object 
 3   Branch                   1000 non-null   object 
 4   City                     1000 non-null   object 
 5   Customer type            1000 non-null   object 
 6   Gender                   1000 non-null   object 
 7   Payment                  1000 non-null   object 
 8   Product line             1000 non-null   object 
 9   Unit price               1000 non-null   float64
 10  Quantity                 1000 non-null   int64  
 11  Tax 5%                   1000 non-null   float64
 12  Total                    1000 non-null   float64
 13  cogs                     1000 non-null   float64
 14  gross margin percentage  

In [5]:
X = dataset.iloc[:,3:15].values
y = dataset.iloc[:,-2].values

In [6]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [7]:
print(X)

[[0.0 1.0 'A' ... 457.44300000000004 435.66 4.7619047619999995]
 [0.0 1.0 'A' ... 399.756 380.72 4.7619047619999995]
 [1.0 0.0 'B' ... 470.673 448.26 4.7619047619999995]
 ...
 [1.0 0.0 'A' ... 216.84599999999998 206.52 4.7619047619999995]
 [1.0 0.0 'A' ... 469.77 447.4 4.7619047619999995]
 [0.0 1.0 'C' ... 304.983 290.46 4.7619047619999995]]


In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [2])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [9]:
print(X)

[[1.0 0.0 0.0 ... 457.44300000000004 435.66 4.7619047619999995]
 [1.0 0.0 0.0 ... 399.756 380.72 4.7619047619999995]
 [0.0 1.0 0.0 ... 470.673 448.26 4.7619047619999995]
 ...
 [1.0 0.0 0.0 ... 216.84599999999998 206.52 4.7619047619999995]
 [1.0 0.0 0.0 ... 469.77 447.4 4.7619047619999995]
 [0.0 0.0 1.0 ... 304.983 290.46 4.7619047619999995]]


In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [5])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [11]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [8])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [12]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [10])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [13]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [13])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [15]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [16]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=1)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[29.  29. ]
 [16.4 16.4]
 [ 3.2  3.2]
 [45.3 45.2]
 [ 4.9  4.9]
 [17.5 17.5]
 [ 2.7  2.7]
 [23.2 23.2]
 [ 1.6  1.6]
 [ 8.8  8.8]
 [ 5.3  5.3]
 [10.2 10.2]
 [ 2.8  2.8]
 [ 7.   7. ]
 [ 7.9  7.9]
 [12.2 12.2]
 [17.2 17.2]
 [23.6 23.6]
 [24.3 24.3]
 [24.8 24.8]
 [18.3 18.3]
 [15.4 15.4]
 [12.2 12.2]
 [45.  45. ]
 [ 4.7  4.7]
 [25.5 25.5]
 [20.6 20.6]
 [12.1 12.1]
 [20.1 20.1]
 [19.  19. ]
 [21.  21. ]
 [ 8.2  8.2]
 [ 6.5  6.5]
 [35.1 35.1]
 [19.5 19.5]
 [33.4 33.4]
 [ 6.2  6.2]
 [44.6 44.6]
 [ 7.9  7.9]
 [49.5 49.5]
 [ 0.5  0.5]
 [ 4.1  4.1]
 [ 3.3  3.3]
 [21.  21. ]
 [ 7.3  7.3]
 [10.  10. ]
 [ 9.7  9.7]
 [ 3.6  3.6]
 [ 0.8  0.8]
 [ 7.2  7.2]
 [22.7 22.7]
 [22.5 22.5]
 [16.6 16.6]
 [ 9.1  9.1]
 [38.5 38.5]
 [ 3.3  3.3]
 [ 1.   1. ]
 [13.  13. ]
 [25.1 25.1]
 [44.5 44.5]
 [20.  20. ]
 [36.1 36.1]
 [11.4 11.4]
 [ 9.7  9.7]
 [20.8 20.8]
 [ 7.9  7.9]
 [ 1.7  1.7]
 [ 2.7  2.7]
 [18.2 18.2]
 [ 9.2  9.2]
 [ 2.4  2.4]
 [ 1.1  1.1]
 [ 8.7  8.7]
 [37.3 37.3]
 [23.6 23.6]
 [14.3 14.3]
 [48.8 48.8]

In [17]:
x_plot = dataset.iloc[:, [8,10]]  

In [18]:
print(x_plot)

               Product line  Quantity
0         Sports and travel         6
1        Home and lifestyle         8
2    Electronic accessories         6
3         Sports and travel        10
4    Electronic accessories         2
..                      ...       ...
995      Food and beverages         2
996     Fashion accessories         8
997      Home and lifestyle         6
998       Sports and travel         5
999  Electronic accessories         3

[1000 rows x 2 columns]


In [27]:
a = dataset.iloc[:,8].values

In [ ]:
print(a)

In [32]:
for i in range(len(a)):
  if a[i] == "Sports and travel":
    a[i] = 0
  elif a[i] == "Home and lifestyle":
    a[i] = 1
  elif a[i] == "Electronic accessories":
    a[i] = 2
  elif a[i] == "Fashion accessories":
    a[i] = 3
  elif a[i] == "Health and beauty":
    a[i] = 4
  elif a[i] == "Food and beverages":
    a[i] = 5

In [33]:
print(a)

[0 1 2 0 2 4 3 0 2 0 5 5 2 1 0 5 5 4 3 2 5 1 3 4 4 2 3 5 0 3 4 3 2 5 0 0 1
 4 5 1 5 3 2 3 5 0 3 5 2 3 0 3 2 2 0 1 0 0 4 1 0 3 4 2 0 5 2 1 4 4 4 1 4 0
 1 4 5 0 1 3 5 0 0 0 5 1 0 5 5 3 1 1 2 2 5 1 2 4 5 4 4 1 3 2 2 2 0 1 3 4 2
 1 2 1 3 0 3 4 5 2 5 5 0 4 2 2 1 4 4 3 4 1 5 4 3 1 1 1 3 1 3 5 3 4 2 0 4 4
 1 3 5 4 0 3 5 5 2 4 5 5 0 1 3 5 3 3 4 4 4 1 2 0 1 4 5 1 0 3 5 1 4 0 3 3 5
 5 4 4 3 1 2 4 4 5 2 1 0 0 1 5 0 1 2 4 0 2 3 0 3 2 1 3 1 5 0 5 5 4 5 2 1 2
 2 5 1 0 2 3 4 3 0 2 1 2 3 3 1 1 3 4 5 2 1 2 1 3 5 5 1 3 0 0 3 1 0 1 3 2 5
 0 2 5 5 0 3 0 0 3 1 3 4 1 3 0 1 2 2 4 4 3 3 1 5 1 5 5 3 0 3 0 3 1 1 2 2 3
 2 0 5 5 1 3 5 1 4 1 5 2 2 2 0 0 3 4 5 0 3 3 4 5 0 1 3 4 0 0 1 2 3 0 2 5 2
 5 4 0 3 1 2 2 3 3 1 3 0 1 5 5 0 3 5 4 1 2 2 0 3 5 0 5 5 5 1 3 1 4 5 5 0 1
 1 4 1 0 0 1 4 4 5 1 3 2 3 2 0 4 4 3 3 1 2 0 1 2 3 1 4 5 2 0 3 2 4 4 2 0 4
 4 0 5 1 5 1 2 3 2 3 5 0 0 4 5 1 2 5 3 5 5 3 3 0 5 4 4 4 2 0 2 3 5 1 0 5 4
 2 4 1 1 2 3 1 5 0 3 0 0 1 5 0 1 1 0 5 5 1 0 0 5 0 4 2 5 4 1 3 3 0 0 3 1 5
 5 2 1 0 0 0 0 2 5 3 2 2 

In [34]:
plt.scatter(x_plot[a == 0, 0], x_plot[a == 0, 1], s = 100, c = 'red', label = 'Cluster 1')
plt.scatter(x_plot[a == 1, 0], x_plot[a == 1, 1], s = 100, c = 'blue', label = 'Cluster 2')
plt.scatter(x_plot[a == 2, 0], x_plot[a == 2, 1], s = 100, c = 'green', label = 'Cluster 3')
plt.scatter(x_plot[a == 3, 0], x_plot[a == 3, 1], s = 100, c = 'cyan', label = 'Cluster 4')
plt.scatter(x_plot[a == 4, 0], x_plot[a == 4, 1], s = 100, c = 'magenta', label = 'Cluster 5')
plt.scatter(x_plot[a == 5, 0], x_plot[a == 5, 1], s = 100, c = 'orange', label = 'Cluster 6')
plt.scatter(kmeans.cluster_centers_[:, 0], kmeans.cluster_centers_[:, 1], s = 300, c = 'yellow', label = 'Centroids')
plt.title('Clusters of customers')
plt.xlabel('Annual Income (k$)')
plt.ylabel('Spending Score (1-100)')
plt.legend()
plt.show()

TypeError: ignored